trigger:
- develop
- stage

schedules:
  - cron: '30 4 * * *'
    displayName: Daily morning check
    branches:
      include:
      - develop

pool:
  name: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install    
  displayName: 'Install dependencies'

- script: ./node_modules/.bin/cypress run --browser chrome --headless --config "baseUrl=$(CYPRESS_baseUrl)"   
  env:          
    CYPRESS_userPass: $(CYPRESS_USERPASS)
  workingDirectory: ${{variables.projectPath}}
  continueOnError: true
  displayName: 'Run cypress tests'
  
- task: PublishHtmlReport@1
  displayName: 'Publish HTML Report'
  inputs:
    reportDir: './cypress/mochawesome-report/index.html'        
